ManajemenStok/Models/Inventory/StokOpnameViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ManajemenStok.Models.Inventory
{
    public class StokOpnameViewModel
    {
        public string NoBukti { get; set; }
        public DateTime Tanggal { get; set; }
        public int Lokasi { get; set; }
        public int SubKategori { get; set; }
        public string Jenis { get; set; }
        public string Inisial { get; set; }
        public List<StokOpnameDetailViewModel> Detail { get; set; }

        public string Setup { get; set; }
    }

    public class StokOpnameDetailViewModel 
    {
        public int Id { get; set; }
        public double Qty { get; set; }
        public string Keterangan { get; set; }
    }

}

ManajemenStok/Controllers/Inventory/StokOpnameController.cs
using ManajemenStok.Models.Inventory;
using ManajemenStok.Entities.SIM;
using ManajemenStok.Helper;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Xml;

namespace Inventory.Controllers.Inventory
{
    [Authorize(Roles = "Inventory")]
    public class StokOpnameController : Controller
    {
        private string tipepelayanan = "NONE";
        private string tipepelayanan2 = "NONE";

        #region ===== L I S T

        [HttpGet]
        public ActionResult Index()
        {
            var model = new StokOpnameViewModel();
            if (Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan
                && Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan2) return HttpNotFound();
            using (var s = new SIMEntities())
            {
                model.Setup = "1";
                var setup = s.SetupAwal.FirstOrDefault(x => x.SetupName == "QtyFisikOpnameNol");
                if (setup != null)
                {
                    model.Setup = setup.Nilai.ToString();
                }
            }
            ViewBag.Setup = model.Setup;
            return View(model);
        }

        [HttpPost]
        public string List(string orderby, bool orderbytype, int pagesize, int pageindex, List<FilterModel> filter)
        {
            try
            {
                var lokasi = int.Parse(Request.Cookies["Inventory_Section_LokasiId"].Value);

                int totalcount;
                using (var s = new SIMEntities())
                {
                    var proses = s.INV_ListStokOpname.Where(x => x.Lokasi_ID == lokasi).AsQueryable();
                    foreach (var x in filter)
                    {
                        if (x.Key == "All" && !string.IsNullOrEmpty(x.Value))
                        {
                            proses = proses.Where(y => 
                            y.No_Bukti.Contains(x.Value) ||
                            y.KelompokJenis.Contains(x.Value) ||
                            y.Nama_Kategori.Contains(x.Value) ||
                            y.Nama_Sub_Kategori.Contains(x.Value) ||
                            y.Keterangan.Contains(x.Value)
                            );
                        }
                        if (x.Key == "PeriodeStart" && !string.IsNullOrEmpty(x.Value))
                        {
                            var d = DateTime.Parse(x.Value);
                            proses = proses.Where(y => y.Tgl_Opname >= d);
                        }
                        if (x.Key == "PeriodeEnd" && !string.IsNullOrEmpty(x.Value))
                        {
                            var d = DateTime.Parse(x.Value);
                            proses = proses.Where(y => y.Tgl_Opname <= d);
                        }
                    }
                    //var tahun = int.Parse(filter.FirstOrDefault(x => x.Key == "Tahun").Value);
                    //var bulan = int.Parse(filter.FirstOrDefault(x => x.Key == "Bulan").Value);
                    //var _start = new DateTime(tahun, bulan, 1);
                    //var _end = new DateTime(tahun, bulan, DateTime.DaysInMonth(tahun, bulan));
                    //proses = proses.Where(y => y.Tgl_Opname >= _start && y.Tgl_Opname <= _end);

                    totalcount = proses.Count();
                    var models = proses.OrderBy($"{orderby} {(orderbytype ? "ASC" : "DESC")}").Skip((pageindex) * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        No = m.No_Bukti,
                        Posted = m.Posted,
                        Tanggal = m.Tgl_Opname.ToString("dd/MM/yyyy"),
                        Kelompok = m.KelompokJenis,
                        SubKategoriID = m.Nama_Sub_Kategori,
                        SubKategori = m.SubKategori_ID,
                        Keterangan = m.Keterangan
                    });
                    return JsonConvert.SerializeObject(new { IsSuccess = true, Data = r, TotalCount = totalcount });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        #endregion

        #region ===== S E T U P

        [HttpPost]
        public string Save(string _process, StokOpnameViewModel model)
        {
            if (Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan
                && Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan2) return HConvert.Error("Bukan Tipe Pelayanan");
            using (var s = new SIMEntities())
            {
                using (var dbContextTransaction = s.Database.BeginTransaction())
                {
                    try
                    {
                        var userid = User.Identity.GetUserId();
                        string id = "";
                        if (_process == "CREATE")
                        {
                            if (model.Detail == null) model.Detail = new List<StokOpnameDetailViewModel>();
                            if (model.Detail.Count == 0) throw new Exception("Detail tidak boleh kosong");
                            id = s.INV_InsertStokOpname(
                                model.Tanggal,
                                model.Jenis,
                                model.Lokasi,
                                userid,
                                model.SubKategori,
                                model.Inisial
                            ).FirstOrDefault();

                            if (string.IsNullOrEmpty(id)) throw new Exception("INV_InsertStokOpname tidak mendapatkan nobukti");

                            foreach (var x in model.Detail)
                            {
                                s.INV_InsertStokOpnameDetail(
                                    id,
                                    x.Id,
                                    model.Lokasi,
                                    x.Qty,
                                    x.Keterangan
                                );
                            }
                            s.SaveChanges();
                        }
                        else if (_process == "EDIT")
                        {
                            foreach (var x in model.Detail)
                            {
                                s.INV_UpdateStokOpnameDetail(
                                    model.NoBukti,
                                    x.Id,
                                    x.Qty,
                                    x.Keterangan
                                );
                            }
                            s.SaveChanges();
                        }

                        var userActivity = new UserActivityModel(Request, User.Identity.GetUserId())
                        {
                            Activity = $"StokOpname-{_process}; id:{id};".ToLower()
                        };
                        UserActivity.InsertUserActivity(userActivity);
                        dbContextTransaction.Commit();

                        return JsonConvert.SerializeObject(new { IsSuccess = true, Id = id });
                    }
                    catch (SqlException ex) { dbContextTransaction.Rollback(); return HConvert.Error(ex); }
                    catch (Exception ex) { dbContextTransaction.Rollback(); return HConvert.Error(ex); }
                }
            }
        }

        [HttpPost]
        public string Detail(string id)
        {
            if (Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan
                && Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan2) return HConvert.Error("Bukan Tipe Pelayanan");
            try
            {
                using (var s = new SIMEntities())
                {
                    var m = s.INV_ListStokOpnameHeader.FirstOrDefault(x => x.No_Bukti == id);
                    if (m == null) throw new Exception("Data tidak ditemukan");
                    var d = s.INV_ListStokOpnameDetail.Where(x => x.No_Bukti == m.No_Bukti).OrderBy(x => x.Kode_Barang).ToList();
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = new
                        {
                            No = m.No_Bukti,
                            Tanggal = m.Tgl_Opname.ToString("yyyy-MM-dd"),
                            Lokasi = m.Lokasi_ID,
                            SubKategori = m.SubKategori_ID,
                            SubKategoriNama = m.Nama_Sub_Kategori,
                            Posted = m.Posted,
                            Jenis = m.KelompokJenis,
                            Inisial = m.Keterangan
                        },
                        Detail = d.ConvertAll(x => new
                        {
                            Id = x.Barang_ID,
                            Kode = x.Kode_Barang,
                            Nama = x.Nama_Barang,
                            Satuan = x.NamaSatuan,
                            Konversi = x.Konversi,
                            QtySystem = x.Stock_Akhir,
                            QtyFisik = x.Qty_Opname,
                            Harga = x.Harga_Rata,
                            Kategori = x.Nama_Kategori,
                            Keterangan = x.Keterangan
                        })
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        [HttpPost]
        public string ProsesSO(string id)
        {

ManajemenStok/Controllers/ReportController.cs
using ManajemenStok.Helper;
using ManajemenStok.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace ManajemenStok.Controllers
{
    public class ReportController : Controller
    {
        private string serverpath = "~/Reports/";

        public ActionResult Index(string name, string category)
        {
            var hreport = new HReport(Server, serverpath);
            var r = new ReportInventoryViewModel();
            r.Name = name;
            r.Category = category;
            r.Reports = hreport.List(r.Category);
            return View(r);
        }

        public ActionResult ExportPDF(string category, string filename, string param)
        {
            try
            {
                var server = WebConfigurationManager.AppSettings["reportserver"];
                var database = WebConfigurationManager.AppSettings["reportdatabase"];
                var user = WebConfigurationManager.AppSettings["reportuser"];
                var pass = WebConfigurationManager.AppSettings["reportpass"];

                var hreport = new HReport(Server, serverpath);
                var parameters = JsonConvert.DeserializeObject<List<HReportParameter>>(param);
                var stream = hreport.ExportPDF(server, database, user, pass, category, filename, parameters);
                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();
                return File(stream, "application/pdf");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

ManajemenStok/Views/StokOpname/Index.cshtml
@{
    ViewBag.Title = "Stok Opname";
    ViewBag.breadcrumb = new List<SelectListItem>()
{
        new SelectListItem(){ Text = ViewBag.Title, Value = "active" }
    };
}
@using ManajemenStok.Helper
@using Microsoft.AspNet.Identity

<style>
    #formtable table th,
    #formtable table td {
        white-space: nowrap;
    }
</style>

<form id="formtable">
    <div class="panel panel-flat">
        <div class="panel-heading">
            <div class="panel-title"></div>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a class="panel-action action-plus" href="javascript:isetup.opensetup('CREATE')"></a></li>
                    <li><a class="panel-action action-filter" href="javascript:itable.openfilter()"></a></li>
                </ul>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2">
                <label>Filter</label>
                <input type="text" name="all" data-itable-filter="All" class="form-control" />
            </div>
            <div class="col-md-2">
                <label>Dari Tanggal</label>
                <input type="date" name="periode" onchange="itable.pageindex = 0; itable.refresh();" data-itable-filter="PeriodeStart" class="form-control" value="@(DateTime.Today.ToString("yyyy-MM-dd"))" />
            </div>
            <div class="col-md-2">
                <label>Sampai Tanggal</label>
                <input type="date" name="sampai" onchange="itable.pageindex = 0; itable.refresh();" data-itable-filter="PeriodeEnd" class="form-control" value="@(DateTime.Today.ToString("yyyy-MM-dd"))" />
            </div>
            @*<label class="control-label col-md-2">Show</label>*@
            <div class="col-md-1">
                <label>Page</label>
                <select class="form-control itable-pagesize" onchange="itable.pageindex = 0; itable.refresh();" style="width: auto;" name="show">
                    <option selected>10</option>
                    <option>25</option>
                    <option>50</option>
                    <option>100</option>
                </select>
            </div>
            <div class="col-md-2 hide">
                <button type="submit" style="margin-top : 27px" class="btn-save btn btn-primary"><i class="icon icon-search4"></i>Cari</button>
            </div>
        </div>
        <div class="dataTables_wrapper no-footer" style="display: block;">
            <div class="datatable-header">
                <input type="hidden" data-itable-filter="Tahun" value="@DateTime.Today.Year">
                <input type="hidden" data-itable-filter="Bulan" value="@DateTime.Today.Month">
            </div>
            <div class="datatable-scroll">
                <table class="table datatable-basic dataTable no-footer table-xxs table-striped">
                    <thead>
                        <tr class="bg-slate">
                            <th class="sorting" data-itable-sorting="No_Bukti" style="width: 100px;">No Bukti<i></i></th>
                            <th class="sorting" data-itable-sorting="Tgl_Opname" style="width: 100px;">Tanggal<i></i></th>
                            <th class="sorting" data-itable-sorting="KelompokJenis">Jenis<i></i></th>
                            <th class="sorting" data-itable-sorting="Nama_Sub_Kategori">SubKategori<i></i></th>
                            <th class="sorting" data-itable-sorting="Posted">Keterangan<i></i></th>
                            <th class="text-center sorting_disabled" style="width: 100px;">Actions</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <div class="datatable-footer">
                <div class="dataTables_info itable-info"></div>
                <div class="dataTables_paginate paging_simple_numbers itable-pagination"></div>
            </div>
        </div>
    </div>
</form>

<div id="modalfilter" class="modal fade" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <form autocomplete="off" onsubmit="itable.filtersubmit(this,event)">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Filter</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="control-label col-md-4">Filter</label>
                            <div class="col-md-8">
                                <input type="text" name="all" class="form-control" />
                            </div>
                        </div>
                        <div class="hide form-group">
                            <div class="col-md-8">
                                <input type="text" name="lokasiid" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Periode</label>
                            <div class="col-md-8">
                                <input type="date" name="periode" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Sampai</label>
                            <div class="col-md-8">
                                <input type="date" name="sampai" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Show</label>
                            <div class="col-md-8">
                                <select class="form-control" style="width: auto;" name="show">
                                    <option selected>10</option>
                                    <option>25</option>
                                    <option>50</option>
                                    <option>100</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn-save btn btn-primary"><i class="icon icon-check"></i> OK</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    var itable;
    document.addEventListener("DOMContentLoaded", function (event) {
        itable = new iTable({
            url: '@Url.Action("List")',
            table: document.getElementById('formtable'),
            orderby: 'No_Bukti',
            orderbytype: false,
            tablesuccess: function (r, t) {
                if (r.IsSuccess) {
                    var tbody = '';
                    if (r.Data.length === 0)
                        tbody += '<tr><td colspan="6" class="text-center">----- <b>Tidak ada data</b> -----</td></tr>';
                    $.each(r.Data, function (index, value) {
                        tbody += '<tr class="alpha-' + status + '">';

                        // column
                        tbody += '<td>' + value.No + '</td>';
                        tbody += '<td class="text-center">' + value.Tanggal + '</td>';
                        tbody += '<td>' + value.Kelompok + '</td>';
                        tbody += '<td>' + value.SubKategoriID + '</td>';
                        tbody += '<td>' + (value.Posted ? 'Sudah SO' : 'Belum SO') + '</td>';

                        tbody += '<td class="text-center">';
                        tbody += '<ul class="icons-list">';
                        tbody += '<li class="dropdown">';
                        tbody += '<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>';
                        tbody += '<ul class="dropdown-menu dropdown-menu-right">';

                        // action
                        tbody += '<li><a href="javascript:isetup.opensetup(\'VIEW\', { id : \'' + value.No + '\'})"><i class="icon-eye"></i> View</a></li>';
                        if (!value.Posted)
                        tbody += '<li><a href="javascript:isetup.opensetup(\'EDIT\',{ id : \'' + value.No + '\'})"><i class="icon-pencil"></i> Edit</a></li>';
                        tbody += '<li><a target="_blank" href="@Url.Action("ExportPDF", "Report", new { category = "Transaksi", filename= "SIM_Rpt_DataOpname.rpt" })&param=[{\'Name\':\'@@NoBukti\',\'ParameterType\':4,\'Value\':\'' + value.No + '\'}]"><i class="icon-printer"></i> Report</a></li>';

                        tbody += '</ul>';
                        tbody += '</li>';
                        tbody += '</ul>';
                        tbody += '</td>';
                        tbody += '</tr>';
                    });
                    $(t.table).find('tbody').html(tbody);
                    var footer = generatefootertable(r.TotalCount, t.pagesize, t.pageindex, 'tableordergetdatas');
                    $(t.table).find('.itable-info').html(footer.datainfo);
                    $(t.table).find('.itable-pagination').html(footer.pagination);
                } else {
                    alert(r.Message);
                }
            }
        });

        itable.refresh();

        itable.openfilter = function () {
            var f = $('#modalfilter form')[0];
            f['lokasiid'].value = $('#formtable [data-itable-filter="LokasiId"]')[0].value;
            f['periode'].value = $('#formtable [data-itable-filter="PeriodeStart"]')[0].value;
            f['sampai'].value = $('#formtable [data-itable-filter="PeriodeEnd"]')[0].value;
            //f['tahun'].value = $('#formtable [data-itable-filter="Tahun"]')[0].value;
            //f['bulan'].value = $('#formtable [data-itable-filter="Bulan"]')[0].value;
            f['all'].value = $('#formtable [data-itable-filter="All"]')[0].value;
            f['show'].value = $('#formtable .itable-pagesize')[0].value;
            $('#modalfilter').modal();
        }

        itable.filtersubmit = function (t, e) {
            e.preventDefault();
            var f = $('#modalfilter form')[0];
            $('#formtable [data-itable-filter="PeriodeStart"]')[0].value = f['periode'].value;
            $('#formtable [data-itable-filter="PeriodeEnd"]')[0].value = f['sampai'].value;
            $('#formtable [data-itable-filter="LokasiId"]')[0].value = f['lokasiid'].value;
            $('#formtable [data-itable-filter="All"]')[0].value = f['all'].value;
            $('#formtable .itable-pagesize')[0].value = f['show'].value;
            itable.pageindex = 0;
            itable.refresh();
            $('#modalfilter').modal('hide');
        }
    });
</script>
@Html.Partial("_LookUpBarang")
@Html.Partial("Setup")